name: appactions

on: 
  repository_dispatch:
  workflow_dispatch:

# 每天从凌晨3点开始，每隔4小时执行一次（即在3:00, 7:00, 11:00, 15:00, 19:00, 23:00）
  schedule:
    - cron: 0 3,7,11,15,19,23 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  appactions:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt update
        sudo apt install openjdk-18-jdk python3 python3-pip curl wget p7zip p7zip-full zstd aria2 git -y
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
        ##修复root环境无法安装包的问题
        EM=$(sudo ls /usr/lib/python*/EXTERNALLY-MANAGED 2>/dev/null | sed -n '1p')
        [ -f "$EM" ] && sudo mv -f $EM ${EM}.bak
        sudo pip install protobuf==3.20.0
        #lanzou-api
        sudo pip install requests_toolbelt
        sudo pip install lxml click asn1crypto Beautifulsoup4 requests xmltodict dicttoxml python-jsonpath colorama filetype chardet aligo protobuf cryptography pyOpenSSL certifi billiard
        git clone https://${{ secrets._GITHUB_PERSONAL_NAME }}:${{ secrets._GITHUB_PERSONAL_TOKEN }}@github.com/${{ secrets._GITHUB_PERSONAL_NAME }}/${{ secrets._GITHUB_PERSONAL_REPO }}.git
        cd ${{ secrets._GITHUB_PERSONAL_REPO }}
        touch ./passWord.txt
        #echo "${{ secrets._GITHUB_ALI_TOKEN }}" >./aliCloudToken.txt
        echo "${{ secrets._GITHUB_LANZOU_COOKIES_START }}" >./lanzouCloudCookies.txt
        echo "${{ secrets._GITHUB_LANZOU_COOKIES_END }}" >>./lanzouCloudCookies.txt
        echo "${{ secrets._GITHUB_123PAN_USENAME }}" >./123PanUseNameAndPassWord.txt
        echo "${{ secrets._GITHUB_123PAN_PASSWORD }}" >>./123PanUseNameAndPassWord.txt
        echo "${{ secrets._GITHUB_123PAN_LOGINUUID }}" >>./123PanUseNameAndPassWord.txt
        echo "${{ secrets._GITHUB_123PAN_COOKIES }}" >>./pyscript/tool/pan123/123pan.txt

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0

    - name: auto run appactions.py
      run: |
        cd ${{ secrets._GITHUB_PERSONAL_REPO }}
        sudo python ./pyscript/main/appactions.py

    #- name: Upload zip
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: UMSR Patch
    #    path: out/*.zip
