name: autoBuild

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 2,10,18 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  autoBuild:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo -E apt-get install -y openjdk-8-jdk python3 python3-pip curl wget p7zip p7zip-full aria2 git
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
        sudo pip install protobuf Beautifulsoup4 requests xmltodict lanzou-api colorama filetype chardet aligo protobuf six
        git clone https://${{ secrets._GITHUB_PERSONAL_NAME }}:${{ secrets._GITHUB_PERSONAL_TOKEN }}@github.com/${{ secrets._GITHUB_PERSONAL_NAME }}/${{ secrets._GITHUB_PERSONAL_REPO }}.git
        cd ${{ secrets._GITHUB_PERSONAL_REPO }}
        touch ./passWord.txt
        python ./pyscript/toolpy/config.py

    - name: add framework-res
      run: |
        cd ${{ secrets._GITHUB_PERSONAL_REPO }}
        mkdir -p ./framework
        cp -af ./framework-res/*.apk ./framework

    - name: autoBuild
      run: |
        cd ${{ secrets._GITHUB_PERSONAL_REPO }}
        sudo python ./pyscript/mainpy/autoBuild.py

    #- name: Upload Apps
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: MIUIApps
    #    path: out/*.apk
